root            /dev/null;
server_name     $hostname;

add_header X-Content-Type-Options nosniff;
add_header X-Robots-Tag none;
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' ws: wss:;";
