---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@3846ae0fd09acec8ac1ac308ceacd052b9d01bec
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
